### ISSUE TITLE
Problem with IDL inheritance and Python Stubs

### ISSUE THREAD

**Issue by marco-buttu** [discos/discos#141] opened 2017-06-05 11:40 UTC
Getting the `SRTLPBandReceiver`:

```
lp = client.getComponent('RECEIVERS/SRTLPBandReceiver')
  File "/.../ACSSW/lib/python/site-packages/Acspy/Servants/ContainerServices.py",
line 230, in getComponent
    comp_class = self.__importComponentStubs(comp_name, comp_idl_type)
  File "/.../ACSSW/lib/python/site-packages/Acspy/Servants/ContainerServices.py",
    line 318, in __importComponentStubs
  raise CannotGetComponentExImpl(e)
CannotGetComponentExImpl: 
...
shortDescription='Error retrieving component', 
data=TypeError('Error when calling the metaclass bases\n
Cannot create a consistent method resolution\norder (MRO) for bases 
_objref_GenericDerotator, _objref_CharacteristicComponent',), ...))
```

We had a similar problem in ACS-8.2, fixed applying the patch of section [Apply some patch to ACS](https://github.com/discos/deployment/blob/master/ansible/roles/common/tasks/acs.yml), in the [deployment repo](https://github.com/discos/deployment/).

**Comment by giuseppe-carboni** [comment] 2022-12-19 11:54
My guess is that `GenericDerotator` already inherits from `CharacteristicComponent`. This causes a 'diamond inheritance problem'. I faced a similar problem when writing some other component, I solved it by not explicitly inheriting from `CharacteristicComponent` since the parent class of my class was already inheriting from it. No external patch was required.

**Comment by marco-buttu** [comment] 2022-12-19 12:47
@giuseppe-carboni There is a note at the end of my second post: "Notice that the LPBandReceiver does not inherit from GenericDerotator"

**Comment by giuseppe-carboni** [comment] 2022-12-19 13:09
@marco-buttu my bad, I did not notice the second comment and I thought it was a similar issue to #181. This is yet to be investigated.

**Comment by giuseppe-carboni** [comment] 2022-12-19 13:18
In `centos_7_compatibility` branch this does not seem to happen anymore, neither when the ReceiversBoss is configured with LLP configuration nor with the KKG configuration (I tried it since the error mentions `GenericDerotator` multiple times, and we only have a derotator in KKG configuration).

**Comment by marco-buttu** [comment] 2022-12-19 13:32
I think we can close it. I suppose there was something not clean in the introot, and it was importing an interface inherited from GenericDerotator.

**Comment by giuseppe-carboni** [comment] 2022-12-19 17:19
Closing since we cannot reproduce this.

**Closed by giuseppe-carboni** 2022-12-19 17:19 UTC
Labels: line-common
